name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v2
        with:
          name: dirb-mac
          path: ./dirb

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install deps
        run: sudo apt-get install libcurl4-gnutls-dev librtmp-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v2
        with:
          name: dirb-linux
          path: ./dirb

  build-windows:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: cygwin
        uses: cygwin/cygwin-install-action@master 
      - name: add packages
        run: c:\setup.exe  -q -P lynx,autoconf,curl,curl-devel,curl-doc,make,libtool
      - name: configure
        run: bash -c ./configure
      - name: make
        run: bash make
      - name: make check
        run: bash make check
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v2
        with:
          name: dirb-windows.exe
          path: ./dirb.exe
