name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v2
        with:
          name: dirb_mac
          path: |
            ./dirb
            ./wordlists/**/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install deps
        run: sudo apt-get install libcurl4-gnutls-dev librtmp-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v2
        with:
          name: dirb_linux
          path: |
            ./dirb
            ./wordlists/**/*

  build-windows:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: cygwin
        uses: cygwin/cygwin-install-action@master 
        with:
          packages: autoconf,autogen,automake,libtool,make,gcc-g++,mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,curl,libcurl-devel,wget,zlib-devel,zip   
      - run: ls C:\cygwin\bin
      - run: bash -c "autoreconf -vif"
      - name: configure 
        run: bash -c "./configure --prefix=/cygdrive/d/a/dirb/dirb/dist" 
      - run: ls
      - name: make
        run: bash -c "make"
      - name: make check
        run: bash -c "make check"
      - run: copy   ./win32/cygwin1.dll .
      - run: copy   ./win32/cygcurl-4.dll .
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v3
        with:
          name: dirb_windows
          path: | 
            ./dirb.exe
            ./cygcurl-4.dll
            ./cygwin1.dll
            ./wordlists/**/*
            ./dist/**/*
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3   
      - run: zip -r  dirb_linux.zip ./dirb_linux
      - run: zip -r  dirb_mac.zip ./dirb_mac
      - run: zip -r  dirb_windows.zip ./dirb_windows
      - uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            dirb_linux.zip
            dirb_windows.zip
            dirb_mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
